name: 手动输入版本号构建 Docker 镜像
on:
  workflow_dispatch:
    inputs:
      new_version:  # 手动触发时，让用户输入新版本号（如 v1.0.1）
        description: 'v1.0.1'
        required: true
        default: 'v1.0.1'  # 默认值（可改，或让用户每次填）

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码（确保拿到仓库文件）
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      # 2. 登录 GHCR
      - name: 登录 GitHub 容器仓库（GHCR）
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: |
          echo "$DOCKER_PAT" | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      # 3. 登录 Docker Hub
      - name: 登录 Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "$DOCKER_HUB_TOKEN" | docker login --username $DOCKER_HUB_USERNAME --password-stdin

      # 4. 构建镜像（用用户输入的版本号）
      - name: 构建镜像（自定义版本号）
        run: |
          # 从 workflow_dispatch 输入拿新版本号
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          GHCR_IMAGE="ghcr.io/${{ github.actor }}/cpxt"
          DOCKERHUB_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/cpxt"

          # 打双标签：用户填的版本号 + latest
          docker build --no-cache \
            -t $GHCR_IMAGE:$NEW_VERSION \
            -t $GHCR_IMAGE:latest \
            -t $DOCKERHUB_IMAGE:$NEW_VERSION \
            -t $DOCKERHUB_IMAGE:latest \
            .  # 确保根目录有 Dockerfile

      # 5. 推送镜像到 GHCR
      - name: 推送镜像到 GHCR
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          GHCR_IMAGE="ghcr.io/${{ github.actor }}/cpxt"
          docker push $GHCR_IMAGE:$NEW_VERSION
          docker push $GHCR_IMAGE:latest

      # 6. 推送镜像到 Docker Hub
      - name: 推送镜像到 Docker Hub
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          DOCKERHUB_IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/cpxt"
          docker push $DOCKERHUB_IMAGE:$NEW_VERSION
          docker push $DOCKERHUB_IMAGE:latest

      # 7. 验证：查看镜像版本
      - name: 查看本地镜像（含版本号）
        run: |
          echo "当前构建的版本：${{ github.event.inputs.new_version }}"
          docker images | grep cpxt
