name: 构建并推送 Docker 镜像到多平台
on:
  workflow_dispatch:  # 手动触发，在 GitHub 仓库页面手动运行

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 登录 GitHub 容器仓库（GHCR）
      - name: 登录 GHCR
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}  # GHCR 的个人访问令牌
        run: |
          echo "$DOCKER_PAT" | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      # 3. 登录 Docker Hub（需提前在 Secrets 配置 DOCKER_HUB_TOKEN）
      - name: 登录 Docker Hub
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}  # Docker Hub 的令牌
        run: |
          echo "$DOCKER_HUB_TOKEN" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      # 4. 构建 Docker 镜像（命名兼容双平台）
      - name: 构建镜像
        run: |
          # 镜像名格式：同时适配 GHCR 和 Docker Hub
          docker build -t ghcr.io/${{ github.actor }}/cpxt:latest \
                       -t ${{ secrets.DOCKER_HUB_USERNAME }}/cpxt:latest .  

      # 5. 推送镜像到 GHCR
      - name: 推送镜像到 GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/cpxt:latest  

      # 6. 推送镜像到 Docker Hub
      - name: 推送镜像到 Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cpxt:latest  

      # 7. （可选）调试：查看本地镜像列表
      - name: 查看本地镜像
        run: docker images
