name: 构建并推送 Docker 镜像
on:
  workflow_dispatch:  # 改为手动触发，需在 GitHub 仓库页面手动点击运行

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 登录 GitHub 容器仓库（GHCR），使用个人访问令牌
      - name: 登录 GHCR
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}  # 从 Secrets 读取令牌
        run: |
          echo "$DOCKER_PAT" | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      # 3. 构建 Docker 镜像（直接使用环境内置的 Docker）
      - name: 构建镜像
        run: |
          docker build -t ghcr.io/${{ github.actor }}/cpxt:latest .  

      # 4. 推送镜像到 GHCR
      - name: 推送镜像
        run: |
          docker push ghcr.io/${{ github.actor }}/cpxt:latest  

      # 5. （可选）调试：查看本地镜像列表
      - name: 查看本地镜像
        run: docker images
