name: 稳定构建并推送 Docker 镜像
on:
  push:
    branches: [ main ]  # 推送到 main 分支触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 登录 GitHub 镜像仓库（GHCR）
      - name: 登录 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io          # GitHub 镜像仓库地址
          username: ${{ github.actor }}  # 自动填充你的用户名（duoyuya）
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动获取权限

      # 3. 本地构建镜像（用最基础的 docker build）
      - name: 构建 Docker 镜像
        run: |
          docker build -t ghcr.io/duoyuya/cpxt:latest .  # 镜像名固定

      # 4. 推送镜像到 GHCR
      - name: 推送镜像
        run: |
          docker push ghcr.io/duoyuya/cpxt:latest

      # 5. （可选）调试：查看本地镜像
      - name: 查看本地镜像
        run: docker images
