name: 构建并推送 Docker 镜像（个人仓库版）
on:
  push:
    branches: [ main ]  # 推送 main 分支触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 配置 Docker 环境（基础版，避免复杂依赖）
      - name: 安装 Docker CLI
        run: |
          sudo apt update
          sudo apt install -y docker.io

      # 3. 登录 GitHub 容器仓库（GHCR），使用个人访问令牌
      - name: 登录 GHCR
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}  # 从 Secrets 读取令牌
        run: |
          echo "$DOCKER_PAT" | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      # 4. 构建 Docker 镜像（强制使用当前目录）
      - name: 构建镜像
        run: |
          docker build -t ghcr.io/${{ github.actor }}/cpxt:latest .

      # 5. 推送镜像到 GHCR
      - name: 推送镜像
        run: |
          docker push ghcr.io/${{ github.actor }}/cpxt:latest

      # 6. （可选）调试：查看镜像信息
      - name: 查看本地镜像
        run: docker images
