name: Build Docker Image
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: bmcpxt:latest
          no-cache: true
          load: true  # 关键：让镜像可被本地 docker 命令访问

      - name: List Docker images (debug)
        run: |
          echo "=== 构建后镜像列表 ==="
          docker images
          echo "======================"

      - name: Save Docker image
        run: |
          docker save -o docker-image.tar bmcpxt:latest

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar
